### ISSUE TITLE
[8] System error: not a directory

### ISSUE THREAD

**Issue by NemoAlex** [vimagick/dockerfiles#10]
I have put 2 files in ~/fig/shadowvpn/ as example:

```
~/fig/shadowvpn/
├── docker-compose.yml
└── server.conf
```

And when I run `docker-compose up -d`, got this error:
```
Pulling shadowvpn (vimagick/shadowvpn:latest)...
latest: Pulling from vimagick/shadowvpn
d6ead20d5571: Pull complete
c56dc909340f: Pull complete
8cce9a23b88b: Pull complete
5c916c5fe31d: Pull complete
3bfec32a6dc1: Pull complete
Digest: sha256:ddafcb4546f2f7fc8125cb8e3639259fbe8d4c43520aab04b84f9ed0274ddeda
Status: Downloaded newer image for vimagick/shadowvpn:latest
Creating shadowvpn_shadowvpn_1
ERROR: Cannot start container 15fa4ca5f74ef677529ce9b73140c21f0ff7fd85a1e955559402e040cb8a3a50: [8] System error: not a directory
```

**Comment by vimagick** [comment]
Try this `docker-compose.yml`

```
shadowvpn:
  image: vimagick/shadowvpn
  ports:
    - "1123:1123/udp"
  volumes:
    - "./server.conf:/etc/shadowvpn/server.conf"
  privileged: true
  restart: always
```
