### ISSUE TITLE
Cannot use MantisBT SOAP API: 'Array to string conversion'

### ISSUE THREAD

**Issue by PierreBeucher** [vimagick/dockerfiles#14]
Hello,

I run the vimagick/mantisbt container with a linked MySQL container (as described in the README). The server is seemingly running fine when accessed via a browser (creating project and issue is OK). However, most of the SOAP API functions are failing with a Server fault showing:

_'Error Type: SYSTEM NOTICE, Error Description: Array to string conversion'_

When running the same MantisBT server on a plain VM (Ubuntu 14.04) with identical PHP version  SOAP API calls are working fine.

I am using MantisBT 1.2.19 with PHP 5.6.20.

Output of php --version from container:

> PHP 5.6.20 (cli) (built: Apr  5 2016 01:26:25)
> Copyright (c) 1997-2016 The PHP Group
> Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

Output of php --version from comparative VM:

> PHP 5.6.20-1+deb.sury.org~trusty+1 (cli)
> Copyright (c) 1997-2016 The PHP Group
> Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
>     with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Comment by vimagick** [comment]
Sorry, I'm not a PHP expert. I didn't test the SOAP API.
To narrow down the network problem, you can use host network.
Please change `docker-compose.yml` and try again.

```yaml
mantisbt:
  image: vimagick/mantisbt:latest
  net: host
# ports:
#   - "8989:80"
# links:
#   - mysql
  restart: always

mysql:
  image: mysql:latest
  net: host
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=bugtracker
    - MYSQL_USER=mantisbt
    - MYSQL_PASSWORD=mantisbt
  restart: always
```

```
==================================================================
Hostname (for Database Server)                          localhost
==================================================================
```
