### ISSUE TITLE
Noting cached persistently

### ISSUE THREAD

**Issue by Alsan** [vimagick/dockerfiles#176]
Hello, I'm trying to build a "Download server" for our offline development environment by using polipo and docker. I've setup the polipo in my own notbook to test the ability of polipo, so far the cache ability is great, but I can't see any download object persist in the cached folder, so what's wrong with my config?

```yaml
version: "3.8"

services:
  polipo:
    image: vimagick/polipo
    container_name: polipo
    hostname: polipo
    restart: unless-stopped
    command:
      cacheIsShared=false
      socksParentProxy=172.17.0.1:10808
      socksProxyType=socks5
      chunkHighMark=819200
      objectHighMark=128
      pmmFirstSize=16384
      pmmSize=8192
      logLevel=0xFF
    ports:
      - 8123:8123/tcp
    volumes:
      - polipo-cache:/var/cache/polipo:rw
      - polipo-www:/usr/share/polipo/www:ro
    networks:
      - polipo

volumes:
  polipo-cache:
  polipo-www:

networks:
  polipo:
    driver: bridge
```
