### ISSUE TITLE
urlwatch: Help to run urlwatch with docker run

### ISSUE THREAD

**Issue by MrSparklle** [vimagick/dockerfiles#180]
I trying unsuccessful to execute urlwatch through `docker run`:

```
docker run -d  \
  --name=urlwatch \
  -v /storage/.config/docker/urlwatch:/root/.urlwatch \
  vimagick/urlwatch
```

everything install flawlessly:
```
Unable to find image 'vimagick/urlwatch:latest' locally
latest: Pulling from vimagick/urlwatch
5843afab3874: Pull complete 
37cbfd066d84: Pull complete 
c1ef2864ec56: Pull complete 
Digest: sha256:d14f15852ee69774ec5d35fb8e3d17390fa974820f0f06bf71ceb29b245bc241
Status: Downloaded newer image for vimagick/urlwatch:latest
fcee4af2bd615840ebfebb2c59c963344e9e881cbcccc3e94733f8311b27a1bb
```

Inside `/storage/.config/docker/urlwatch` I have a file called `urls.yaml`
```
url: 'https://github.com/thp/urlwatch/releases/latest'
filter:
  - xpath: '(//div[contains(@class,"release-timeline-tags")]//h4)[1]/a'
  - html2text: re
```

After starts the containner immediately stops with error below:
`docker logs urlwatch`

`standard_init_linux.go:219: exec user process caused: exec format error`
