### ISSUE TITLE
Opencart: No such file or directory

### ISSUE THREAD

**Issue by BrunoCodeman** [vimagick/dockerfiles#19]
![captura de tela 2016-06-14 as 18 04 46](https://cloud.githubusercontent.com/assets/407822/16059664/6ffb1d6c-325a-11e6-9eb7-6559069ac836.png)

I'm stuck on this screen trying to stall opencart. Can you give me some help, please?

Thanks!

**Comment by vimagick** [comment]
If you're using this [docker-compose.yml](https://github.com/vimagick/dockerfiles/blob/master/opencart/docker-compose.yml)

```yaml
opencart:
  image: vimagick/opencart
  ports:
    - "8000:80"
  links:
    - mysql
  volumes:
    - /var/www/html
  restart: always

mysql:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=opencart
restart: always
```

The `Hostname` should be `mysql` (not `localhost`).
