### ISSUE TITLE
strongswan: docker run command instead of docker-compose.yml

### ISSUE THREAD

**Issue by AdySan** [vimagick/dockerfiles#52]
Hello,

I'm rather new to docker, haven't picked up docker compose yet.  I'd prefer to run the strongswan image with a `docker run` command. Can you please guide me how to translate this `docker-compose.yml` to a `docker run` command?

```
version: '2'
services:
  strongswan:
    image: vimagick/strongswan
    ports:
      - 500:500/udp
      - 4500:4500/udp
    volumes:
      - /lib/modules:/lib/modules
      - /etc/localtime:/etc/localtime
    environment:
      - VPN_DOMAIN=vpn.easypi.info
      - VPN_NETWORK=10.20.30.0/24
      - LAN_NETWORK=192.168.0.0/16
      - VPN_P12_PASSWORD=secret
    tmpfs: /run
    privileged: yes
    restart: always
```
