### ISSUE TITLE
aria2: token seems to remain at the default value when assigned a new one manually

### ISSUE THREAD

**Issue by BirkhoffLee** [vimagick/dockerfiles#60]
My `docker-compose.yml`: 

```yaml
version: '3'

services:

  aria2:
    image: vimagick/aria2
    container_name: aria2
    ports:
    - "6800:6800"
    environment:
    - "TOKEN=9bfff50c-xxxx-xxxx-xxxx-xxxxxxxxxa99"
    volumes:
    - "./aria2/data:/home/aria2"
    - "./aria2/keys:/etc/aria2/keys"
    - "./aria2/aria2.conf:/etc/aria2/aria2.conf"

  ariang:
    build: ariang
    container_name: ariang
    expose:
    - 80
    environment:
    - "VIRTUAL_HOST=xxxx.birkhoff.me"
    links:
    - "aria2"

networks:
  default:
    external:
      name: aria2
```

`aria2.conf`:

```properties
dir=/home/aria2
disable-ipv6=true
enable-rpc=true
max-download-limit=0
max-upload-limit=0
rpc-allow-origin-all=true
rpc-certificate=/etc/aria2/keys/server.crt
rpc-listen-all=true
rpc-listen-port=6800
rpc-private-key=/etc/aria2/keys/server.key
rpc-secret=9bfff50c-xxxx-xxxx-xxxx-xxxxxxxxxa99
seed-ratio=0
seed-time=0
```

`docker-compose up -d`:

```
aria2     | + chown -R aria2:aria2 /home/aria2
aria2     | + gosu aria2 aria2c --conf-path=/etc/aria2/aria2.conf --rpc-secret=00000000-0000-0000-0000-000000000000
aria2     |
aria2     | 10/20 02:16:29 [NOTICE] RPC transport will be encrypted.
aria2     |
aria2     | 10/20 02:16:29 [NOTICE] IPv4 RPC: listening on TCP port 6800
```

Notice that it still remains on `00000000-0000-0000-0000-000000000000` instead of `9bfff50c-xxxx-xxxx-xxxx-xxxxxxxxxa99` that I assigned manually. Thoughts?
