### ISSUE TITLE
(vimagick/scrapyd) How to use this images deploy my scrapy ? thanks

### ISSUE THREAD

**Issue by brotherYoung** [vimagick/dockerfiles#86]
now ,i do this:
docker exec -it xxx(id) bash , cd /xxx, then scrapyd-deploy 
other better way?

**Comment by vimagick** [comment]
Please use this docker-compose.yml to run container.

```yaml
scrapyd:
  image: vimagick/scrapyd
  ports:
    - "6800:6800"
  volumes:
    - ./data:/var/lib/scrapyd
    - /usr/local/lib/python2.7/dist-packages
  restart: always
```
