### ISSUE TITLE
ImportError: No module named scrapyd.scripts.scrapyd_run

### ISSUE THREAD

**Issue by philiphoyos** [vimagick/dockerfiles#97]
docker-compose.yml
```
scrapyd:
  image: vimagick/scrapyd
  ports:
    - "6800:6800"
  volumes:
    - ./data:/var/lib/scrapyd
    - /usr/local/lib/python2.7/dist-packages
  restart: always
```

Using ` docker-compose up` yields the following

```
Creating docker-scrapyd_scrapyd_1 ... done
Attaching to docker-scrapyd_scrapyd_1
scrapyd_1  | Traceback (most recent call last):
scrapyd_1  |   File "/usr/local/bin/scrapyd", line 7, in <module>
scrapyd_1  |     from scrapyd.scripts.scrapyd_run import main
scrapyd_1  | ImportError: No module named scrapyd.scripts.scrapyd_run
```

Any clue to what I could be doing wrong?
